### ISSUE TITLE
How to get speaker embedding?

### ISSUE THREAD

**Issue by cnlinxi** [mycrazycracy/speaker-embedding-with-phonetic-information#1]
Great work!
How can I get speaker embedding for one audio by this repo? Thank you.

**Comment by mycrazycracy** [comment]
Please follow the v2/run.sh.
I assume you are familiar with Kaldi. If you have one wav file, you can use make_mfcc to extract the features. Then use sid/nnet3_cvector/cvector/extract_xvectors_new.sh to extract the speaker embedding into ark file.
Please let me know if you have any problems.
